name: Feature Request
description: File a new feature request
labels: ["feature"]
title: "[Feature] "
projects: ["Cell_UnitFrames/1"]
assignees:
  - Krealle
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to submit your feature request.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: Please give a brief overview (1-2 sentences) of what you would like to see added.
      placeholder: I'd really love it if you would be able to...
    validations:
      required: true
  - type: textarea
    id: feature-implementation
    attributes:
      label: Describe the implementation
      description: Describe how you would like to see this feature implemented
      placeholder: When changing the layout of Unit, I would like abc option, so I can do xyz.
    validations:
      required: true
